import { createServer } from 'http';
import { readFile } from 'fs/promises';
import { renderToPipeableStream } from 'react-server-dom-webpack/server';
import React from 'react';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = 3000;

// Simple HTTP server
const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);

  try {
    if (url.pathname === '/') {
      // Serve the initial HTML page
      res.setHeader('Content-Type', 'text/html');
      res.end(`
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>React Server Components - Hello World</title>
          </head>
          <body>
            <div id="root">Loading...</div>
            <script type="module" src="/client.js"></script>
          </body>
        </html>
      `);
    } else if (url.pathname === '/rsc') {
      // Serve the React Server Component payload
      // This is the magic! The server renders the component tree
      // and streams it to the client as a special format

      // Dynamically import the server component
      const ServerComponent = (await import('./src/ServerComponent.jsx')).default;

      // Create a client manifest (in a real setup, this would be generated by webpack)
      const clientManifest = {};

      const { pipe } = renderToPipeableStream(
        React.createElement(ServerComponent),
        clientManifest
      );

      res.setHeader('Content-Type', 'text/x-component');
      pipe(res);
    } else if (url.pathname === '/client.js') {
      // Serve the bundled client JavaScript
      const clientJs = await readFile(path.join(__dirname, 'public', 'client.js'), 'utf-8');
      res.setHeader('Content-Type', 'application/javascript');
      res.end(clientJs);
    } else {
      res.statusCode = 404;
      res.end('Not found');
    }
  } catch (error) {
    console.error('Server error:', error);
    res.statusCode = 500;
    res.end('Internal server error');
  }
});

server.listen(PORT, () => {
  console.log(`🚀 Server running at http://localhost:${PORT}`);
  console.log('');
  console.log('📘 What\'s happening:');
  console.log('  1. The server renders React components on the server');
  console.log('  2. Server Components are NOT sent to the browser');
  console.log('  3. Only Client Components are hydrated in the browser');
  console.log('  4. The /rsc endpoint streams the component tree to the client');
  console.log('');
  console.log('Open http://localhost:3000 in your browser!');
});
